export const AdminTypes = {
    CREATE_NEW_MODEL_REQUEST: 'CREATE_NEW_MODEL_REQUEST',
    CREATE_NEW_MODEL_SUCCESS: 'CREATE_NEW_MODEL_SUCCESS',
    CREATE_NEW_MODEL_FAILURE: 'CREATE_NEW_MODEL_FAILURE',

    DELETE_MODEL_REQUEST: 'DELETE_MODEL_REQUEST',
    DELETE_MODEL_SUCCESS: 'DELETE_MODEL_SUCCESS',
    DELETE_MODEL_FAILURE: 'DELETE_MODEL_FAILURE',

    SWITCH_USER_STATUS_REQUEST: 'SWITCH_USER_STATUS_REQUEST',
    SWITCH_USER_STATUS_SUCCESS: 'SWITCH_USER_STATUS_SUCCESS',
    SWITCH_USER_STATUS_FAILURE: 'SWITCH_USER_STATUS_FAILURE',

    GET_USERS_REQUEST: 'GET_USERS_REQUEST',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',

    GET_MODELS_REQUEST: 'GET_MODELS_REQUEST',
    GET_MODELS_SUCCESS: 'GET_MODELS_SUCCESS',
    GET_MODELS_FAILURE: 'GET_MODELS_FAILURE'
}