export const UserTypes = {
    GET_USER_INFO_REQUEST: 'GET_USER_INFO_REQUEST', 
    GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS', 
    GET_USER_INFO_FAILURE: 'GET_USER_INFO_FAILURE',

    GET_VOTING_STATS_REQUEST: 'GET_VOTING_STATS_REQUEST', 
    GET_VOTING_STATS_SUCCESS: 'GET_VOTING_STATS_SUCCESS', 
    GET_VOTING_STATS_FAILURE: 'GET_VOTING_STATS_FAILURE',

    EDIT_PROFILE_REQUEST: 'EDIT_PROFILE_REQUEST', 
    EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS', 
    EDIT_PROFILE_FAILURE: 'EDIT_PROFILE_FAILURE'
} 