export const VotingTypes = {
    GET_PAIR_REQUEST: 'GET_PAIR_REQUEST',
    GET_PAIR_SUCCESS: 'GET_PAIR_SUCCESS',
    GET_PAIR_FAILURE: 'GET_PAIR_FAILURE',
    
    VOTE_REQUEST: 'VOTE_REQUEST',
    VOTE_SUCCESS: 'VOTE_SUCCESS',
    VOTE_FAILURE: 'VOTE_FAILURE',

    RESET_VOTES_REQUEST: 'RESET_VOTES_REQUEST',
    RESET_VOTES_SUCCESS: 'RESET_VOTES_SUCCESS',
    RESET_VOTES_FAILURE: 'RESET_VOTES_FAILURE'
}